name: 'Generate tfvars'
description: 'Gera arquivo terraform.tfvars com base em variáveis dinâmicas e segredos'

inputs:
  AWS_REGION:
    required: true
  PROJECT_NAME:
    required: true
  ENVIRONMENT:
    required: true
  GLOBAL_ENV_VARS_JSON:
    required: true
  ENVIRONMENTS:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  s3_bucket_name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Gerar arquivo terraform.tfvars
      shell: bash
      run: |
        echo "Gerando terraform.tfvars..."

        mkdir -p terraform

        S3_BUCKET_NAME=$(echo '${{ inputs.GLOBAL_ENV_VARS_JSON }}' | jq -r '.S3_BUCKET_NAME')

        echo "aws_region = \"${{ inputs.AWS_REGION }}\""        > terraform/terraform.tfvars
        echo "project_name = \"${{ inputs.PROJECT_NAME }}\""   >> terraform/terraform.tfvars
        echo "environment = \"${{ inputs.ENVIRONMENT }}\""     >> terraform/terraform.tfvars
        echo "s3_bucket_name = \"${S3_BUCKET_NAME}\""          >> terraform/terraform.tfvars
        echo "global_env_vars = ${{ inputs.GLOBAL_ENV_VARS_JSON }}" >> terraform/terraform.tfvars
        echo "environments = ${{ inputs.ENVIRONMENTS }}"            >> terraform/terraform.tfvars

        echo "Conteúdo gerado em terraform/terraform.tfvars:"
        cat terraform/terraform.tfvars


    - name: Verificar acesso ao bucket S3
      shell: bash
      run: aws s3 ls s3://${{ inputs.s3_bucket_name }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: ${{ inputs.AWS_REGION }}

    - name: Validar credenciais AWS (STS)
      shell: bash
      run: aws sts get-caller-identity
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
        AWS_REGION: ${{ inputs.AWS_REGION }}

    - name: Debug variáveis de entrada
      shell: bash
      run: |
        echo "project_name=${{ inputs.PROJECT_NAME }}"
        echo "environment=${{ inputs.ENVIRONMENT }}"
        echo "s3_bucket_name=${{ inputs.s3_bucket_name }}"
        echo "aws_region=${{ inputs.AWS_REGION }}"
