name: Dynamic Lambda Deployment

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch:

env: # Variáveis globais disponíveis para todos os jobs
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # -------------------------------
      # 🧾 CHECKOUT
      # -------------------------------
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # -------------------------------
      # 🧾 Steps
      # -------------------------------
      - name: Setup Node.js and Env Vars
        id: setup_node
        uses: ./.github/actions/setup-node
        with:
          node_version: '20'

      - name: Install & Build
        id: install_build
        uses: ./.github/actions/build-package
        with:
          project_name: ${{ env.PROJECT_NAME }}
        
      - name: Upload Lambda to S3
        id: upload-lambda-to-s3
        uses: ./.github/actions/upload-to-s3
        with:
          global_env_vars_json: ${{ secrets.GLOBAL_ENV_VARS_JSON }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          project_name: ${{ env.PROJECT_NAME }}

      - name: Setup Terraform
        id: setup_terraform
        uses: ./.github/actions/setup-terraform
        with:
          terraform_version: '1.5.6'
          environment: ${{ env.ENVIRONMENT }}
          project_name: ${{ env.PROJECT_NAME }}
          s3_bucket_name: ${{ env.S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate tfvars
        id: generate_tvars
        uses: ./.github/actions/generate-tfvars
        with:
          environments: ${{ secrets.ENVIRONMENTS }}
          global_env_vars_json: ${{ secrets.GLOBAL_ENV_VARS_JSON }}
          s3_bucket_name: ${{ env.S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          project_name: ${{ env.PROJECT_NAME }}
          environment: ${{ env.ENVIRONMENT }}
        
      - name: Importar recursos existentes
        id: import_resources
        uses: ./.github/actions/import-resources
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          project_name: ${{ env.PROJECT_NAME }}
          environment: ${{ env.ENVIRONMENT }}
        
      - name: Validar Terraform
        id: validate_terraform
        uses: ./.github/actions/validate-terraform
        with:
          terraform_path: terraform

      - name: Terraform Plan and Apply
        id: plan_apply_terraform
        uses: ./.github/actions/plan-apply-terraform
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
